services:
  db:
    image: postgres
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
    networks:
      - app_network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app_network

volumes:
  postgres_db:

networks:
  app_network:
