services:
  db:
    image: postgres
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
    networks:
      - app_network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app_network

  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: docker
      MINIO_ROOT_PASSWORD: docker@123
    networks:
      - app_network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - app_network

volumes:
  postgres_db:
  minio_data:

networks:
  app_network:
